spring:
  # 配置mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${kill.mysql.host}:${kill.mysql.port}/morningstar?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${kill.mysql.username}
    password: ${kill.mysql.password}
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initial-size: 6
      # 最小连接池数量
      min-idle: 2
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      max-wait: 60000
  data:
    # 配置mongodb数据源
    mongodb:
      username: root
      password: 1234asdw
      host: localhost
      port: 27017
      database: morningstar
      authentication-database: admin

# 配置mybatis
mybatis-plus:
  type-aliases-package: com.morningstar.kill.pojo
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 通过mybatis执行的sql以日志方式输出到终端
#  type-handlers-package: com.morningstar.kill.dao.type # 目前直接使用注解注册
  global-config:
    db-config:
      logic-delete-field: isDeleted # 约定全局删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0

# pagehelper配置
pagehelper:
  helper-dialect: mysql # 指定分页数据库类型(方言)【某些数据库可能不支持limit】
  reasonable: true # 合理查询: e.g. 超过最大页，则查询最后一页
